"""
Run from the backend folder:
    .\venv\Scripts\python.exe seed.py
"""

from app.database import SessionLocal
from app.models.course import Course
from app.models.topic import Topic
from app.models.question import Question, QuestionType, Difficulty

DATA = [
    {
        "title": "JavaScript Fundamentals",
        "slug": "javascript",
        "description": "Master the core concepts of JavaScript — the language of the web.",
        "language": "javascript",
        "icon": "js",
        "order": 1,
        "topics": [
            {
                "title": "Variables & Data Types",
                "slug": "variables-data-types",
                "description": "Learn about var, let, const and JavaScript's dynamic type system.",
                "order": 1,
                "questions": [
                    # EASY
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which keyword declares a block-scoped variable in JavaScript?",
                        "options": [{"label": "A", "text": "var"}, {"label": "B", "text": "let"}, {"label": "C", "text": "define"}, {"label": "D", "text": "static"}],
                        "correct_answer": "B",
                        "explanation": "`let` declares a block-scoped variable. `var` is function-scoped, and `define`/`static` are not valid JS keywords for variable declaration.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What is the output of `typeof null` in JavaScript?",
                        "options": [{"label": "A", "text": "null"}, {"label": "B", "text": "undefined"}, {"label": "C", "text": "object"}, {"label": "D", "text": "boolean"}],
                        "correct_answer": "C",
                        "explanation": "`typeof null` returns `'object'` — this is a long-standing bug in JavaScript that was kept for backwards compatibility.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Complete: To declare a constant in JavaScript, use the `___` keyword.",
                        "correct_answer": "const",
                        "explanation": "`const` declares a variable whose binding cannot be reassigned. The value itself may still be mutable (e.g. an object's properties).",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which of the following is NOT a primitive type in JavaScript?",
                        "options": [{"label": "A", "text": "string"}, {"label": "B", "text": "number"}, {"label": "C", "text": "array"}, {"label": "D", "text": "boolean"}],
                        "correct_answer": "C",
                        "explanation": "Arrays are objects in JavaScript, not primitives. The primitive types are: string, number, bigint, boolean, undefined, symbol, and null.",
                        "points": 10,
                    },
                    # MEDIUM
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the output of this code?",
                        "code_block": "let x = 5;\nlet y = '5';\nconsole.log(x == y);",
                        "correct_answer": "true",
                        "explanation": "`==` uses type coercion, so `5 == '5'` is `true`. Use `===` for strict equality that also checks type.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What does this code log?",
                        "code_block": "console.log(0.1 + 0.2 === 0.3);",
                        "correct_answer": "false",
                        "explanation": "Due to floating-point precision, `0.1 + 0.2` equals `0.30000000000000004`, not `0.3`. This is a common JavaScript gotcha.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is logged?",
                        "code_block": "var a = 1;\n{\n  var a = 2;\n}\nconsole.log(a);",
                        "correct_answer": "2",
                        "explanation": "`var` is function-scoped, not block-scoped. The inner `var a = 2` overwrites the outer `a`, so `2` is logged.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the result of `typeof undefined`?",
                        "options": [{"label": "A", "text": "null"}, {"label": "B", "text": "undefined"}, {"label": "C", "text": "object"}, {"label": "D", "text": "void"}],
                        "correct_answer": "B",
                        "explanation": "`typeof undefined` returns the string `'undefined'`. Unlike `typeof null`, this one behaves as expected.",
                        "points": 15,
                    },
                    # HARD
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is the output?",
                        "code_block": "console.log([] + []);\nconsole.log([] + {});\nconsole.log({} + []);",
                        "correct_answer": "[object Object]",
                        "explanation": "`[] + []` is `''`, `[] + {}` is `'[object Object]'`. The last line `{} + []` in a statement context treats `{}` as an empty block, so it becomes `+[]` which is `0`. But in console context all three lines log separately.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.DEBUGGING,
                        "difficulty": Difficulty.HARD,
                        "question_text": "This code should check if a value is strictly a number (not NaN). Fix it.",
                        "code_block": "function isNumber(val) {\n  return typeof val === 'number';\n}",
                        "correct_answer": "function isNumber(val) {\n  return typeof val === 'number' && !isNaN(val);\n}",
                        "explanation": "`typeof NaN === 'number'` is `true` in JavaScript, so you must also check `!isNaN(val)` to exclude NaN.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What does this log?",
                        "code_block": "let a = 'foo';\nlet b = a;\nb = 'bar';\nconsole.log(a);",
                        "correct_answer": "foo",
                        "explanation": "Strings are primitives and are copied by value. Reassigning `b` does not affect `a`.",
                        "points": 20,
                    },
                ],
            },
            {
                "title": "Functions & Scope",
                "slug": "functions-scope",
                "description": "Understand function declarations, expressions, arrow functions, and closures.",
                "order": 2,
                "questions": [
                    # EASY
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which is the correct arrow function syntax?",
                        "options": [{"label": "A", "text": "function = () => {}"}, {"label": "B", "text": "const fn = () => {}"}, {"label": "C", "text": "const fn = function => {}"}, {"label": "D", "text": "fn() => {}"}],
                        "correct_answer": "B",
                        "explanation": "Arrow functions use the syntax `const fn = () => {}`. They are anonymous and must be assigned to a variable.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.EASY,
                        "question_text": "A function inside another function that accesses the outer function's variables is called a ___.",
                        "correct_answer": "closure",
                        "explanation": "A closure is a function that retains access to its outer (enclosing) scope even after the outer function has returned.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What does a function return if no `return` statement is specified?",
                        "options": [{"label": "A", "text": "0"}, {"label": "B", "text": "null"}, {"label": "C", "text": "undefined"}, {"label": "D", "text": "false"}],
                        "correct_answer": "C",
                        "explanation": "In JavaScript, a function with no `return` statement (or a bare `return`) implicitly returns `undefined`.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Function declarations are hoisted. What does this mean?",
                        "options": [{"label": "A", "text": "They run faster"}, {"label": "B", "text": "They can be called before they are defined in the code"}, {"label": "C", "text": "They are global"}, {"label": "D", "text": "They auto-execute"}],
                        "correct_answer": "B",
                        "explanation": "Hoisting moves function declarations to the top of their scope at compile time, so you can call them before their definition in the source code.",
                        "points": 10,
                    },
                    # MEDIUM
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is logged?",
                        "code_block": "function outer() {\n  let count = 0;\n  return function() {\n    count++;\n    return count;\n  };\n}\nconst inc = outer();\nconsole.log(inc());\nconsole.log(inc());",
                        "correct_answer": "1\n2",
                        "explanation": "`outer()` returns a closure that remembers `count`. Each call to `inc()` increments and returns it, so the output is 1 then 2.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What does this log?",
                        "code_block": "const greet = (name = 'World') => `Hello, ${name}!`;\nconsole.log(greet());\nconsole.log(greet('Dev'));",
                        "correct_answer": "Hello, World!\nHello, Dev!",
                        "explanation": "Default parameters are used when the argument is `undefined` or not provided. `greet()` uses `'World'`, `greet('Dev')` uses `'Dev'`.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the key difference between arrow functions and regular functions regarding `this`?",
                        "options": [{"label": "A", "text": "Arrow functions have their own `this`"}, {"label": "B", "text": "Arrow functions inherit `this` from the enclosing scope"}, {"label": "C", "text": "Arrow functions cannot use `this`"}, {"label": "D", "text": "There is no difference"}],
                        "correct_answer": "B",
                        "explanation": "Arrow functions do not have their own `this`. They lexically inherit `this` from the surrounding scope, which avoids common bugs with callbacks.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the output?",
                        "code_block": "function add(...nums) {\n  return nums.reduce((a, b) => a + b, 0);\n}\nconsole.log(add(1, 2, 3, 4));",
                        "correct_answer": "10",
                        "explanation": "The rest parameter `...nums` collects all arguments into an array. `reduce` sums them: 1+2+3+4 = 10.",
                        "points": 15,
                    },
                    # HARD
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is logged and why?",
                        "code_block": "for (var i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}",
                        "correct_answer": "3\n3\n3",
                        "explanation": "`var` is function-scoped, so all three callbacks share the same `i`. By the time the timeouts fire, the loop has finished and `i` is 3. Use `let` to fix this.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.DEBUGGING,
                        "difficulty": Difficulty.HARD,
                        "question_text": "Fix this function so it correctly memoizes results.",
                        "code_block": "function memoize(fn) {\n  const cache = {};\n  return function(n) {\n    if (cache[n]) return cache[n];\n    cache[n] = fn(n);\n  };\n}",
                        "correct_answer": "function memoize(fn) {\n  const cache = {};\n  return function(n) {\n    if (cache[n] !== undefined) return cache[n];\n    cache[n] = fn(n);\n    return cache[n];\n  };\n}",
                        "explanation": "Two bugs: `if (cache[n])` is falsy when the cached result is `0` or `false` — use `!== undefined` instead. Also the result was never returned.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is the output?",
                        "code_block": "const obj = {\n  name: 'Alice',\n  greet: function() {\n    const inner = () => `Hi, ${this.name}`;\n    return inner();\n  }\n};\nconsole.log(obj.greet());",
                        "correct_answer": "Hi, Alice",
                        "explanation": "The arrow function `inner` captures `this` from `greet`, where `this` is `obj`. So `this.name` is `'Alice'`.",
                        "points": 20,
                    },
                ],
            },
            {
                "title": "Arrays & Loops",
                "slug": "arrays-loops",
                "description": "Work with arrays using map, filter, reduce and modern iteration patterns.",
                "order": 3,
                "questions": [
                    # EASY
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which array method adds an element to the END of an array?",
                        "options": [{"label": "A", "text": "unshift()"}, {"label": "B", "text": "push()"}, {"label": "C", "text": "append()"}, {"label": "D", "text": "add()"}],
                        "correct_answer": "B",
                        "explanation": "`push()` adds one or more elements to the end of an array and returns the new length. `unshift()` adds to the beginning.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What is logged?",
                        "code_block": "const arr = [1, 2, 3];\nconsole.log(arr.length);",
                        "correct_answer": "3",
                        "explanation": "The `.length` property returns the number of elements in the array. `[1, 2, 3]` has 3 elements.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.EASY,
                        "question_text": "The array method that creates a NEW array with all elements that pass a test is called `___`.",
                        "correct_answer": "filter",
                        "explanation": "`filter()` returns a new array containing only elements for which the callback returns `true`. The original array is not mutated.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which loop is best for iterating over array values directly?",
                        "options": [{"label": "A", "text": "for...in"}, {"label": "B", "text": "for...of"}, {"label": "C", "text": "while"}, {"label": "D", "text": "do...while"}],
                        "correct_answer": "B",
                        "explanation": "`for...of` iterates over iterable values (arrays, strings, etc.). `for...in` iterates over object keys/indices and should be avoided for arrays.",
                        "points": 10,
                    },
                    # MEDIUM
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the output?",
                        "code_block": "const nums = [1, 2, 3, 4, 5];\nconst result = nums.filter(n => n % 2 === 0).map(n => n * 10);\nconsole.log(result);",
                        "correct_answer": "[20, 40]",
                        "explanation": "`filter` keeps even numbers `[2, 4]`, then `map` multiplies each by 10 giving `[20, 40]`.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What does this log?",
                        "code_block": "const a = [1, 2];\nconst b = [...a, 3, 4];\nconsole.log(b);",
                        "correct_answer": "[1, 2, 3, 4]",
                        "explanation": "The spread operator `...a` expands the array inline. `b` is a new array `[1, 2, 3, 4]`.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the result?",
                        "code_block": "const total = [1, 2, 3, 4].reduce((acc, val) => acc + val, 0);\nconsole.log(total);",
                        "correct_answer": "10",
                        "explanation": "`reduce` accumulates values. Starting at 0: 0+1=1, 1+2=3, 3+3=6, 6+4=10.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What does `Array.from({length: 3}, (_, i) => i)` return?",
                        "options": [{"label": "A", "text": "[1, 2, 3]"}, {"label": "B", "text": "[0, 1, 2]"}, {"label": "C", "text": "[undefined, undefined, undefined]"}, {"label": "D", "text": "[3, 3, 3]"}],
                        "correct_answer": "B",
                        "explanation": "`Array.from` with a map function receives `(value, index)`. Since values are `undefined`, we use `_` and return the index `i`, giving `[0, 1, 2]`.",
                        "points": 15,
                    },
                    # HARD
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is logged?",
                        "code_block": "const arr = [1, [2, [3, [4]]]];\nconsole.log(arr.flat(Infinity));",
                        "correct_answer": "[1, 2, 3, 4]",
                        "explanation": "`flat(Infinity)` recursively flattens all nested arrays regardless of depth, resulting in `[1, 2, 3, 4]`.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.DEBUGGING,
                        "difficulty": Difficulty.HARD,
                        "question_text": "This function should remove duplicate values from an array. Fix it.",
                        "code_block": "function unique(arr) {\n  return arr.filter((item, index) => {\n    return arr.indexOf(item) !== index;\n  });\n}",
                        "correct_answer": "function unique(arr) {\n  return arr.filter((item, index) => {\n    return arr.indexOf(item) === index;\n  });\n}",
                        "explanation": "`indexOf` returns the FIRST index of an item. Keeping elements where `indexOf === index` means we keep only the first occurrence. The bug was `!==` instead of `===`.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is the output?",
                        "code_block": "const matrix = [[1,2],[3,4],[5,6]];\nconst flat = matrix.reduce((acc, row) => acc.concat(row), []);\nconsole.log(flat);",
                        "correct_answer": "[1, 2, 3, 4, 5, 6]",
                        "explanation": "`reduce` concatenates each row into the accumulator, flattening the 2D array into `[1, 2, 3, 4, 5, 6]`.",
                        "points": 20,
                    },
                ],
            },
        ],
    },
    {
        "title": "Python Basics",
        "slug": "python",
        "description": "Learn Python from the ground up — clean syntax, powerful features.",
        "language": "python",
        "icon": "py",
        "order": 2,
        "topics": [
            {
                "title": "Variables & Data Types",
                "slug": "variables-data-types",
                "description": "Explore Python's dynamic typing, built-in types, and type conversion.",
                "order": 1,
                "questions": [
                    # EASY
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which of the following is a valid way to create a string in Python?",
                        "options": [{"label": "A", "text": "x = 'hello'"}, {"label": "B", "text": "x = hello"}, {"label": "C", "text": "string x = 'hello'"}, {"label": "D", "text": "x := hello"}],
                        "correct_answer": "A",
                        "explanation": "Strings in Python are created by wrapping text in single `'` or double `\"` quotes. No type declaration is needed.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What function returns the type of a variable in Python?",
                        "options": [{"label": "A", "text": "typeof()"}, {"label": "B", "text": "gettype()"}, {"label": "C", "text": "type()"}, {"label": "D", "text": "vartype()"}],
                        "correct_answer": "C",
                        "explanation": "`type()` returns the type of an object. For example, `type(42)` returns `<class 'int'>`.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.EASY,
                        "question_text": "In Python, the boolean value for 'false' is written as `___` (capital first letter).",
                        "correct_answer": "False",
                        "explanation": "Python booleans are `True` and `False` — note the capital first letter. Lowercase `true`/`false` are not valid.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What is the output?",
                        "code_block": "x = 10\ny = 3\nprint(x // y)",
                        "correct_answer": "3",
                        "explanation": "`//` is floor division in Python. `10 // 3 = 3` (the result is rounded down to the nearest integer).",
                        "points": 10,
                    },
                    # MEDIUM
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What does this print?",
                        "code_block": "x = '5'\ny = int(x) + 5\nprint(y)",
                        "correct_answer": "10",
                        "explanation": "`int('5')` converts the string to the integer 5. Adding 5 gives 10.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is printed?",
                        "code_block": "a = [1, 2, 3]\nb = a\nb.append(4)\nprint(a)",
                        "correct_answer": "[1, 2, 3, 4]",
                        "explanation": "Lists are mutable objects. `b = a` does NOT copy the list — both `a` and `b` point to the same object. Mutating `b` also changes `a`.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the result of `bool('')` in Python?",
                        "options": [{"label": "A", "text": "True"}, {"label": "B", "text": "False"}, {"label": "C", "text": "None"}, {"label": "D", "text": "Error"}],
                        "correct_answer": "B",
                        "explanation": "Empty strings are falsy in Python. `bool('')` returns `False`. Non-empty strings like `'0'` return `True`.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the output?",
                        "code_block": "x = None\nprint(x is None)\nprint(x == None)",
                        "correct_answer": "True\nTrue",
                        "explanation": "Both are `True`, but `is None` is the preferred Pythonic way. `is` checks identity (same object), `==` checks equality.",
                        "points": 15,
                    },
                    # HARD
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is the output?",
                        "code_block": "a = (1, 2, 3)\nprint(type(a))\nprint(a[1])",
                        "correct_answer": "<class 'tuple'>\n2",
                        "explanation": "`(1, 2, 3)` creates a tuple. Tuples are immutable sequences. Indexing works the same as lists — `a[1]` is `2`.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.DEBUGGING,
                        "difficulty": Difficulty.HARD,
                        "question_text": "This code should safely convert a string to int and return 0 on failure. Fix it.",
                        "code_block": "def to_int(s):\n    return int(s)",
                        "correct_answer": "def to_int(s):\n    try:\n        return int(s)\n    except ValueError:\n        return 0",
                        "explanation": "`int()` raises a `ValueError` for invalid strings like `'abc'`. Wrapping in `try/except ValueError` lets us return a default value instead.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is printed?",
                        "code_block": "x = [1, 2, 3, 4, 5]\nprint(x[1:4])\nprint(x[::2])",
                        "correct_answer": "[2, 3, 4]\n[1, 3, 5]",
                        "explanation": "`x[1:4]` slices from index 1 up to (not including) 4: `[2, 3, 4]`. `x[::2]` takes every 2nd element: `[1, 3, 5]`.",
                        "points": 20,
                    },
                ],
            },
            {
                "title": "Functions",
                "slug": "functions",
                "description": "Write reusable Python functions with parameters, defaults, and *args/**kwargs.",
                "order": 2,
                "questions": [
                    # EASY
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which keyword is used to define a function in Python?",
                        "options": [{"label": "A", "text": "function"}, {"label": "B", "text": "func"}, {"label": "C", "text": "def"}, {"label": "D", "text": "fn"}],
                        "correct_answer": "C",
                        "explanation": "Python uses `def` to define functions. Example: `def my_func(): pass`",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.EASY,
                        "question_text": "A function that calls itself is called a ___ function.",
                        "correct_answer": "recursive",
                        "explanation": "A recursive function is one that calls itself. Every recursive function needs a base case to stop the recursion.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What is the output?",
                        "code_block": "def greet(name='World'):\n    return f'Hello, {name}!'\n\nprint(greet())\nprint(greet('Python'))",
                        "correct_answer": "Hello, World!\nHello, Python!",
                        "explanation": "Default parameter `name='World'` is used when no argument is passed. `greet('Python')` overrides the default.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What does `*args` allow in a Python function?",
                        "options": [{"label": "A", "text": "Keyword arguments"}, {"label": "B", "text": "Any number of positional arguments"}, {"label": "C", "text": "Default values"}, {"label": "D", "text": "Return multiple values"}],
                        "correct_answer": "B",
                        "explanation": "`*args` collects any extra positional arguments into a tuple, allowing a function to accept a variable number of arguments.",
                        "points": 10,
                    },
                    # MEDIUM
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is printed?",
                        "code_block": "def add(*args):\n    return sum(args)\n\nprint(add(1, 2, 3))\nprint(add(10, 20))",
                        "correct_answer": "6\n30",
                        "explanation": "`*args` collects all positional arguments. `sum([1,2,3])=6` and `sum([10,20])=30`.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What does this print?",
                        "code_block": "square = lambda x: x ** 2\nprint(square(4))\nprint(square(7))",
                        "correct_answer": "16\n49",
                        "explanation": "Lambda functions are anonymous one-liners. `square(4)` returns `4**2 = 16`, `square(7)` returns `7**2 = 49`.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the difference between `*args` and `**kwargs`?",
                        "options": [{"label": "A", "text": "*args is for strings, **kwargs for numbers"}, {"label": "B", "text": "*args collects positional args as a tuple, **kwargs collects keyword args as a dict"}, {"label": "C", "text": "They are identical"}, {"label": "D", "text": "**kwargs is for optional args, *args for required"}],
                        "correct_answer": "B",
                        "explanation": "`*args` packs extra positional arguments into a tuple. `**kwargs` packs extra keyword arguments into a dictionary.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the output?",
                        "code_block": "def counter():\n    count = 0\n    def increment():\n        nonlocal count\n        count += 1\n        return count\n    return increment\n\nc = counter()\nprint(c())\nprint(c())",
                        "correct_answer": "1\n2",
                        "explanation": "`nonlocal` allows the inner function to modify the outer function's `count` variable. Each call increments and returns it.",
                        "points": 15,
                    },
                    # HARD
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is printed?",
                        "code_block": "def apply(func, lst):\n    return [func(x) for x in lst]\n\nresult = apply(lambda x: x**2, [1, 2, 3, 4])\nprint(result)",
                        "correct_answer": "[1, 4, 9, 16]",
                        "explanation": "`apply` maps a function over a list using list comprehension. Squaring each element gives `[1, 4, 9, 16]`.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.DEBUGGING,
                        "difficulty": Difficulty.HARD,
                        "question_text": "Fix this function so it doesn't use a mutable default argument.",
                        "code_block": "def append_item(item, lst=[]):\n    lst.append(item)\n    return lst",
                        "correct_answer": "def append_item(item, lst=None):\n    if lst is None:\n        lst = []\n    lst.append(item)\n    return lst",
                        "explanation": "Mutable default arguments in Python are shared across all calls. Using `None` as default and creating a new list inside the function avoids this classic bug.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What does this print?",
                        "code_block": "def make_multiplier(n):\n    return lambda x: x * n\n\ndouble = make_multiplier(2)\ntriple = make_multiplier(3)\nprint(double(5))\nprint(triple(5))",
                        "correct_answer": "10\n15",
                        "explanation": "`make_multiplier` returns a closure that captures `n`. `double` captures `n=2`, `triple` captures `n=3`. Calling them with 5 gives 10 and 15.",
                        "points": 20,
                    },
                ],
            },
            {
                "title": "Lists & Dictionaries",
                "slug": "lists-dictionaries",
                "description": "Master Python's most used data structures and their powerful methods.",
                "order": 3,
                "questions": [
                    # EASY
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "How do you access the value for key 'name' in a dictionary `d`?",
                        "options": [{"label": "A", "text": "d.name"}, {"label": "B", "text": "d['name']"}, {"label": "C", "text": "d->name"}, {"label": "D", "text": "d.get_key('name')"}],
                        "correct_answer": "B",
                        "explanation": "Dictionary values are accessed using square bracket notation `d['key']` or `d.get('key')` for a safe access that doesn't raise an error.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What is printed?",
                        "code_block": "fruits = ['apple', 'banana', 'cherry']\nprint(fruits[-1])",
                        "correct_answer": "cherry",
                        "explanation": "Negative indexing in Python counts from the end. `fruits[-1]` is the last element, `'cherry'`.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.EASY,
                        "question_text": "To get all keys from a dictionary `d`, use `d.___()` .",
                        "correct_answer": "keys",
                        "explanation": "`d.keys()` returns a view of all keys. Similarly, `d.values()` returns values and `d.items()` returns key-value pairs.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which method removes and returns the last element of a list?",
                        "options": [{"label": "A", "text": "remove()"}, {"label": "B", "text": "delete()"}, {"label": "C", "text": "pop()"}, {"label": "D", "text": "discard()"}],
                        "correct_answer": "C",
                        "explanation": "`pop()` removes and returns the last element by default. `pop(i)` removes and returns the element at index `i`.",
                        "points": 10,
                    },
                    # MEDIUM
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the output?",
                        "code_block": "d = {'a': 1, 'b': 2, 'c': 3}\nresult = {k: v * 2 for k, v in d.items()}\nprint(result)",
                        "correct_answer": "{'a': 2, 'b': 4, 'c': 6}",
                        "explanation": "Dictionary comprehension iterates over `d.items()` (key-value pairs) and creates a new dict with each value doubled.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is printed?",
                        "code_block": "nums = [3, 1, 4, 1, 5, 9, 2, 6]\nprint(sorted(nums))\nprint(nums)",
                        "correct_answer": "[1, 1, 2, 3, 4, 5, 6, 9]\n[3, 1, 4, 1, 5, 9, 2, 6]",
                        "explanation": "`sorted()` returns a NEW sorted list without modifying the original. `nums.sort()` would sort in place.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What does `d.get('missing', 'default')` return when the key doesn't exist?",
                        "options": [{"label": "A", "text": "None"}, {"label": "B", "text": "KeyError"}, {"label": "C", "text": "default"}, {"label": "D", "text": "False"}],
                        "correct_answer": "C",
                        "explanation": "`dict.get(key, default)` returns the value if the key exists, otherwise returns the default value (second argument). It never raises a `KeyError`.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the output?",
                        "code_block": "squares = [x**2 for x in range(1, 6)]\nprint(squares)",
                        "correct_answer": "[1, 4, 9, 16, 25]",
                        "explanation": "List comprehension `[x**2 for x in range(1, 6)]` creates squares of numbers 1 through 5.",
                        "points": 15,
                    },
                    # HARD
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is printed?",
                        "code_block": "from collections import Counter\nwords = ['apple', 'banana', 'apple', 'cherry', 'banana', 'apple']\nc = Counter(words)\nprint(c.most_common(2))",
                        "correct_answer": "[('apple', 3), ('banana', 2)]",
                        "explanation": "`Counter` counts occurrences. `most_common(2)` returns the 2 most frequent items as a list of `(item, count)` tuples.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.DEBUGGING,
                        "difficulty": Difficulty.HARD,
                        "question_text": "Fix this function that should merge two dictionaries, with values from `b` overriding `a`.",
                        "code_block": "def merge(a, b):\n    a.update(b)\n    return a",
                        "correct_answer": "def merge(a, b):\n    result = {**a, **b}\n    return result",
                        "explanation": "The original mutates `a` directly with `update()`. Using `{**a, **b}` creates a new dictionary so the original `a` is not modified.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.PREDICT_OUTPUT,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is printed?",
                        "code_block": "data = [{'name': 'Alice', 'age': 30}, {'name': 'Bob', 'age': 25}]\nsorted_data = sorted(data, key=lambda x: x['age'])\nprint(sorted_data[0]['name'])",
                        "correct_answer": "Bob",
                        "explanation": "Sorting by `'age'` ascending puts Bob (25) before Alice (30). `sorted_data[0]` is Bob's dict, so `['name']` is `'Bob'`.",
                        "points": 20,
                    },
                ],
            },
        ],
    },
    {
        "title": "HTML & CSS",
        "slug": "html-css",
        "description": "Build and style web pages with semantic HTML and modern CSS.",
        "language": "html",
        "icon": "html",
        "order": 3,
        "topics": [
            {
                "title": "HTML Basics",
                "slug": "html-basics",
                "description": "Learn semantic HTML, document structure, and common elements.",
                "order": 1,
                "questions": [
                    # EASY
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which HTML tag is used for the largest heading?",
                        "options": [{"label": "A", "text": "<h6>"}, {"label": "B", "text": "<heading>"}, {"label": "C", "text": "<h1>"}, {"label": "D", "text": "<header>"}],
                        "correct_answer": "C",
                        "explanation": "`<h1>` is the largest/most important heading. Headings go from `<h1>` (largest) to `<h6>` (smallest).",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.EASY,
                        "question_text": "The HTML attribute that specifies the URL of a link is `___`.",
                        "correct_answer": "href",
                        "explanation": "`href` (Hypertext REFerence) is the attribute of the `<a>` tag that defines the destination URL: `<a href='https://example.com'>`.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which tag creates an unordered (bulleted) list?",
                        "options": [{"label": "A", "text": "<ol>"}, {"label": "B", "text": "<list>"}, {"label": "C", "text": "<ul>"}, {"label": "D", "text": "<bl>"}],
                        "correct_answer": "C",
                        "explanation": "`<ul>` creates an unordered list with bullet points. `<ol>` creates an ordered (numbered) list. Both use `<li>` for list items.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What does the `alt` attribute on an `<img>` tag do?",
                        "options": [{"label": "A", "text": "Sets the image title"}, {"label": "B", "text": "Provides alternative text for accessibility and when image fails to load"}, {"label": "C", "text": "Sets the image size"}, {"label": "D", "text": "Links the image to a URL"}],
                        "correct_answer": "B",
                        "explanation": "`alt` provides alternative text displayed when the image can't load, and read by screen readers for accessibility. It's required for valid HTML.",
                        "points": 10,
                    },
                    # MEDIUM
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "Which HTML5 element is most appropriate for the main navigation of a website?",
                        "options": [{"label": "A", "text": "<div class='nav'>"}, {"label": "B", "text": "<nav>"}, {"label": "C", "text": "<menu>"}, {"label": "D", "text": "<navigation>"}],
                        "correct_answer": "B",
                        "explanation": "`<nav>` is a semantic HTML5 element specifically for navigation links. Using semantic elements improves accessibility and SEO.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the correct way to include an external CSS file?",
                        "options": [{"label": "A", "text": "<style src='styles.css'>"}, {"label": "B", "text": "<css href='styles.css'>"}, {"label": "C", "text": "<link rel='stylesheet' href='styles.css'>"}, {"label": "D", "text": "<script href='styles.css'>"}],
                        "correct_answer": "C",
                        "explanation": "External CSS is linked using `<link rel='stylesheet' href='styles.css'>` inside the `<head>` tag.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "The HTML element that represents a self-contained piece of content (like an article or blog post) is `<___>`.",
                        "correct_answer": "article",
                        "explanation": "`<article>` represents a self-contained composition that could be independently distributed, like a blog post, news article, or forum post.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the difference between `<section>` and `<div>`?",
                        "options": [{"label": "A", "text": "No difference"}, {"label": "B", "text": "<section> is semantic and represents a thematic grouping; <div> is a generic container"}, {"label": "C", "text": "<div> is for layout, <section> is for text only"}, {"label": "D", "text": "<section> can only be used once per page"}],
                        "correct_answer": "B",
                        "explanation": "`<section>` is a semantic element indicating a thematic group of content, typically with a heading. `<div>` is a non-semantic container with no inherent meaning.",
                        "points": 15,
                    },
                    # HARD
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.HARD,
                        "question_text": "Which meta tag is essential for responsive web design?",
                        "options": [{"label": "A", "text": "<meta name='responsive' content='true'>"}, {"label": "B", "text": "<meta name='viewport' content='width=device-width, initial-scale=1'>"}, {"label": "C", "text": "<meta name='mobile' content='yes'>"}, {"label": "D", "text": "<meta name='scale' content='1'>"}],
                        "correct_answer": "B",
                        "explanation": "The viewport meta tag `<meta name='viewport' content='width=device-width, initial-scale=1'>` tells the browser to match the device width and set initial zoom to 1, enabling responsive design.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.DEBUGGING,
                        "difficulty": Difficulty.HARD,
                        "question_text": "Fix this form so the input is properly associated with its label for accessibility.",
                        "code_block": "<label>Email</label>\n<input type='email' name='email'>",
                        "correct_answer": "<label for='email'>Email</label>\n<input type='email' id='email' name='email'>",
                        "explanation": "A label is associated with an input using matching `for` (on the label) and `id` (on the input) attributes. This enables clicking the label to focus the input and helps screen readers.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is the purpose of the `<figure>` and `<figcaption>` elements?",
                        "options": [{"label": "A", "text": "They are just styled divs"}, {"label": "B", "text": "They semantically group media (images, diagrams) with their caption"}, {"label": "C", "text": "They create image galleries"}, {"label": "D", "text": "They are used for charts only"}],
                        "correct_answer": "B",
                        "explanation": "`<figure>` wraps self-contained media content and `<figcaption>` provides its caption. Together they create a semantic association between the media and its description.",
                        "points": 20,
                    },
                ],
            },
            {
                "title": "CSS Selectors & Box Model",
                "slug": "css-selectors-box-model",
                "description": "Target elements precisely and understand how CSS calculates layout.",
                "order": 2,
                "questions": [
                    # EASY
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which CSS selector targets an element with `id='header'`?",
                        "options": [{"label": "A", "text": ".header"}, {"label": "B", "text": "*header"}, {"label": "C", "text": "#header"}, {"label": "D", "text": "@header"}],
                        "correct_answer": "C",
                        "explanation": "`#` targets elements by their `id` attribute. `.` targets by class, and element selectors use the tag name directly (e.g. `div`).",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.EASY,
                        "question_text": "The CSS property that controls the space INSIDE an element's border is `___`.",
                        "correct_answer": "padding",
                        "explanation": "`padding` is the space between the content and the border. `margin` is the space outside the border.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What does `color` property control in CSS?",
                        "options": [{"label": "A", "text": "Background color"}, {"label": "B", "text": "Border color"}, {"label": "C", "text": "Text color"}, {"label": "D", "text": "All colors"}],
                        "correct_answer": "C",
                        "explanation": "The `color` property sets the text (foreground) color. Use `background-color` for the background and `border-color` for the border.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "In the box model, what is the order from inside to outside?",
                        "options": [{"label": "A", "text": "content → border → padding → margin"}, {"label": "B", "text": "content → padding → border → margin"}, {"label": "C", "text": "margin → padding → border → content"}, {"label": "D", "text": "padding → content → border → margin"}],
                        "correct_answer": "B",
                        "explanation": "The CSS box model layers are: content (innermost), then padding, then border, then margin (outermost).",
                        "points": 10,
                    },
                    # MEDIUM
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What does `box-sizing: border-box` do?",
                        "options": [{"label": "A", "text": "Removes the border"}, {"label": "B", "text": "Makes width/height include padding and border"}, {"label": "C", "text": "Adds a border to all elements"}, {"label": "D", "text": "Removes margins"}],
                        "correct_answer": "B",
                        "explanation": "With `border-box`, the `width` and `height` you set include the padding and border, making sizing more predictable. The default `content-box` excludes them.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "Which selector targets `<p>` elements that are DIRECT children of a `<div>`?",
                        "options": [{"label": "A", "text": "div p"}, {"label": "B", "text": "div > p"}, {"label": "C", "text": "div + p"}, {"label": "D", "text": "div ~ p"}],
                        "correct_answer": "B",
                        "explanation": "`div > p` is the child combinator — it targets only `<p>` elements that are direct children of `<div>`. `div p` targets any descendant, not just direct children.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "To select every other row in a table, you would use the pseudo-class `:nth-child(___)` with the value `2n`.",
                        "correct_answer": "2n",
                        "explanation": "`:nth-child(2n)` selects every even-numbered child. You can also write `:nth-child(even)`. `:nth-child(2n+1)` or `:nth-child(odd)` selects odd ones.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is CSS specificity?",
                        "options": [{"label": "A", "text": "How fast CSS loads"}, {"label": "B", "text": "The rule that determines which CSS declaration wins when multiple rules target the same element"}, {"label": "C", "text": "How many selectors a file can have"}, {"label": "D", "text": "The order of CSS properties"}],
                        "correct_answer": "B",
                        "explanation": "Specificity is a weight system that determines which CSS rule takes precedence. Inline styles > IDs > Classes/attributes > Elements. Higher specificity wins.",
                        "points": 15,
                    },
                    # HARD
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.HARD,
                        "question_text": "In CSS specificity, what is the order from HIGHEST to LOWEST?",
                        "options": [{"label": "A", "text": "element > class > id > inline"}, {"label": "B", "text": "inline > id > class > element"}, {"label": "C", "text": "id > inline > class > element"}, {"label": "D", "text": "class > id > element > inline"}],
                        "correct_answer": "B",
                        "explanation": "Specificity order: inline styles (1,0,0,0) > id selectors (0,1,0,0) > class/attribute/pseudo-class (0,0,1,0) > element/pseudo-element (0,0,0,1).",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.DEBUGGING,
                        "difficulty": Difficulty.HARD,
                        "question_text": "This CSS should center a `div` horizontally on the page. Fix it.",
                        "code_block": "div {\n  width: 200px;\n  margin: auto;\n  display: inline;\n}",
                        "correct_answer": "div {\n  width: 200px;\n  margin: 0 auto;\n  display: block;\n}",
                        "explanation": "`margin: auto` only works for horizontal centering on block-level elements with a defined width. `display: inline` prevents this — it must be `block`.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What does `position: sticky` do?",
                        "options": [{"label": "A", "text": "Fixes the element to the viewport always"}, {"label": "B", "text": "Keeps the element in normal flow until a scroll threshold, then sticks to a position"}, {"label": "C", "text": "Same as position: fixed"}, {"label": "D", "text": "Removes the element from normal flow"}],
                        "correct_answer": "B",
                        "explanation": "`position: sticky` is a hybrid — the element scrolls normally until it hits a defined threshold (like `top: 0`), then it 'sticks' to that position until its parent scrolls away.",
                        "points": 20,
                    },
                ],
            },
            {
                "title": "Flexbox & Layout",
                "slug": "flexbox-layout",
                "description": "Build modern, responsive layouts with CSS Flexbox.",
                "order": 3,
                "questions": [
                    # EASY
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What CSS property enables Flexbox on a container?",
                        "options": [{"label": "A", "text": "flex: true"}, {"label": "B", "text": "display: flex"}, {"label": "C", "text": "layout: flex"}, {"label": "D", "text": "position: flex"}],
                        "correct_answer": "B",
                        "explanation": "`display: flex` turns an element into a flex container, enabling flexbox layout for its direct children (flex items).",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.EASY,
                        "question_text": "To center flex items along the MAIN axis, use `justify-content: ___`.",
                        "correct_answer": "center",
                        "explanation": "`justify-content: center` centers flex items along the main axis (horizontal by default). Other values: `flex-start`, `flex-end`, `space-between`, `space-around`.",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "What does `flex-direction: column` do?",
                        "options": [{"label": "A", "text": "Arranges items horizontally"}, {"label": "B", "text": "Arranges items vertically (top to bottom)"}, {"label": "C", "text": "Wraps items to the next line"}, {"label": "D", "text": "Reverses item order"}],
                        "correct_answer": "B",
                        "explanation": "`flex-direction: column` changes the main axis to vertical, stacking flex items from top to bottom. The default is `row` (horizontal).",
                        "points": 10,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.EASY,
                        "question_text": "Which property aligns flex items along the CROSS axis?",
                        "options": [{"label": "A", "text": "justify-content"}, {"label": "B", "text": "align-items"}, {"label": "C", "text": "flex-align"}, {"label": "D", "text": "cross-align"}],
                        "correct_answer": "B",
                        "explanation": "`align-items` aligns flex items along the cross axis (perpendicular to main axis). `justify-content` controls the main axis.",
                        "points": 10,
                    },
                    # MEDIUM
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What does `flex: 1` mean on a flex item?",
                        "options": [{"label": "A", "text": "The item takes exactly 1px"}, {"label": "B", "text": "The item takes up all available space equally with other flex:1 items"}, {"label": "C", "text": "The item is the first item"}, {"label": "D", "text": "The item doesn't grow or shrink"}],
                        "correct_answer": "B",
                        "explanation": "`flex: 1` is shorthand for `flex-grow: 1; flex-shrink: 1; flex-basis: 0`. Items with `flex: 1` share available space equally.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "How do you perfectly center a div both horizontally and vertically using Flexbox?",
                        "options": [
                            {"label": "A", "text": "display: flex; margin: auto"},
                            {"label": "B", "text": "display: flex; justify-content: center; align-items: center"},
                            {"label": "C", "text": "display: flex; text-align: center; vertical-align: middle"},
                            {"label": "D", "text": "display: flex; position: center"}
                        ],
                        "correct_answer": "B",
                        "explanation": "`justify-content: center` centers on the main axis (horizontal by default) and `align-items: center` centers on the cross axis (vertical by default).",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.FILL_BLANK,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "To allow flex items to wrap onto multiple lines, set `flex-___: wrap`.",
                        "correct_answer": "wrap",
                        "explanation": "`flex-wrap: wrap` allows flex items to wrap to the next line when they don't fit. The default is `nowrap`, which forces all items onto one line.",
                        "points": 15,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.MEDIUM,
                        "question_text": "What is the default value of `flex-direction`?",
                        "options": [{"label": "A", "text": "column"}, {"label": "B", "text": "row-reverse"}, {"label": "C", "text": "row"}, {"label": "D", "text": "column-reverse"}],
                        "correct_answer": "C",
                        "explanation": "The default `flex-direction` is `row`, which arranges flex items horizontally from left to right.",
                        "points": 15,
                    },
                    # HARD
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What is the difference between `align-items` and `align-content`?",
                        "options": [
                            {"label": "A", "text": "They are identical"},
                            {"label": "B", "text": "align-items aligns items within a single line; align-content aligns multiple lines within the container"},
                            {"label": "C", "text": "align-content is for the main axis"},
                            {"label": "D", "text": "align-items only works on grid"}
                        ],
                        "correct_answer": "B",
                        "explanation": "`align-items` controls alignment within a single flex line. `align-content` only applies when there are multiple lines (with `flex-wrap: wrap`) and controls the spacing between those lines.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.DEBUGGING,
                        "difficulty": Difficulty.HARD,
                        "question_text": "Fix this CSS so the nav items are spaced evenly across the full width of the navbar.",
                        "code_block": ".navbar {\n  display: flex;\n}\n\n.nav-item {\n  margin: 0 10px;\n}",
                        "correct_answer": ".navbar {\n  display: flex;\n  justify-content: space-between;\n}\n\n.nav-item {\n  flex: 1;\n  text-align: center;\n}",
                        "explanation": "Adding `justify-content: space-between` distributes items evenly. `flex: 1` on items makes them share space equally. Fixed margins don't adapt to different screen sizes.",
                        "points": 20,
                    },
                    {
                        "type": QuestionType.MCQ,
                        "difficulty": Difficulty.HARD,
                        "question_text": "What does `order: -1` do to a flex item?",
                        "options": [
                            {"label": "A", "text": "Removes the item from the layout"},
                            {"label": "B", "text": "Moves the item to appear before items with higher order values"},
                            {"label": "C", "text": "Reverses the item's content"},
                            {"label": "D", "text": "Makes the item overlap others"}
                        ],
                        "correct_answer": "B",
                        "explanation": "The `order` property controls the visual order of flex items. Items are sorted by order value (lowest first). Default is `0`, so `order: -1` moves an item before all default items.",
                        "points": 20,
                    },
                ],
            },
        ],
    },
]


def seed():
    db = SessionLocal()
    try:
        if db.query(Course).count() > 0:
            print("Already seeded — courses exist. Delete them first if you want to re-seed.")
            return

        total_questions = 0
        for course_data in DATA:
            course = Course(
                title=course_data["title"],
                slug=course_data["slug"],
                description=course_data["description"],
                language=course_data["language"],
                icon=course_data["icon"],
                order=course_data["order"],
                is_published=True,
            )
            db.add(course)
            db.flush()

            for topic_data in course_data["topics"]:
                topic = Topic(
                    course_id=course.id,
                    title=topic_data["title"],
                    slug=topic_data["slug"],
                    description=topic_data["description"],
                    order=topic_data["order"],
                    is_published=True,
                )
                db.add(topic)
                db.flush()

                for q in topic_data["questions"]:
                    question = Question(
                        topic_id=topic.id,
                        type=q["type"],
                        difficulty=q["difficulty"],
                        question_text=q["question_text"],
                        code_block=q.get("code_block"),
                        options=q.get("options"),
                        correct_answer=q["correct_answer"],
                        explanation=q["explanation"],
                        points=q["points"],
                        is_published=True,
                    )
                    db.add(question)
                    total_questions += 1

        db.commit()
        print(f"Seeded: {len(DATA)} courses, {sum(len(c['topics']) for c in DATA)} topics, {total_questions} questions.")
    except Exception as e:
        db.rollback()
        print(f"Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
